apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-rstgdhrg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-rstgdhrg 
  name: go-rstgdhrg
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-rstgdhrg
    weight: 100 
